### PR TITLE
Update marjanne story

### PR DESCRIPTION
**Pull request by SarahAlidoost**
The new version of powerpoint is Deltares_Marjanne_vesrion2 on sharepoint.

### CODE REVIEW

**Comment by SarahAlidoost** [comment]
@geek-yang I noticed that the size of the card of this story is smaller than others on the home page (main branch), please see [here](https://eucp-project.github.io/storyboards/). any ideas why?

**Review by geek-yang — APPROVED** [review]
Looks good!

**Comment by geek-yang** [comment]
> @geek-yang I noticed that the size of the card of this story is smaller than others on the home page (main branch), please see [here](https://eucp-project.github.io/storyboards/). any ideas why?

@SarahAlidoost I think this is because the style of the card is defined to follow the maximum width of the figure. In this case the ratio (let's say, height/width) is large, therefore it looks smaller. I think we can save this figure with some margin, just like
intro

**Comment by SarahAlidoost** [comment]
> > @geek-yang I noticed that the size of the card of this story is smaller than others on the home page (main branch), please see [here](https://eucp-project.github.io/storyboards/). any ideas why?
> 
> @SarahAlidoost I think this is because the style of the card is defined to follow the maximum width of the figure. In this case the ratio (let's say, height/width) is large, therefore it looks smaller. I think we can save this figure with some margin, just like intro

@geek-yang thanks for reviewing and addressing the issue. Resizing the figure worked. :+1:  See my last commit.

**Comment by Peter9192** [comment]
> I think this is because the style of the card is defined to follow the maximum width of the figure

That's correct. An alternative solution would be to fix the width of the cards. I wasn't sure when I first chose this. If the variability would have been larger, I think flexibility would be better. But now that they're almost equal size but not quite, I agree that it would make sense to try and make them equal.

**Comment by Peter9192** [comment]
Also: the storyboard could still use some extra text. Particularly, this sentence should still be changed: "Html clickable model performance 131 stations -> interactive is nice​"

**Pull request merged**
