### PR TITLE
Fix routing issues

### LINKED ISSUE #6: Routing issues
The landing page on GH pages is hosted `eucp-project.github.io/usecases`. The path to a single use case is `eucp-project.github.io/usecases/usecase_0/panel_1`, but navigating directly to that page on GH returns a 404.

### PR DESCRIPTION
**Pull request by geek-yang**
- use the feature of [Complex Slide Title & Content]() in Vueper Slides to load images and add link
- replace `:link=` with `NuxtLink` function to fix the routing

closes #6

### CODE REVIEW

**Comment by geek-yang** [comment]
For more explaination, see the issue #6 .

**Comment by geek-yang** [comment]
Btw, thanks for your inspiration!!! @Peter9192

**Review by Peter9192 — CHANGES_REQUESTED** [review]
Hi Yang,

I think you've fixed one of our 2 routing problems. The generated links now seem to work correctly in the carousel. However, we also found the issue related to the 404 as described in #6. I don't think you've addressed that yet. Can you add it here?

**Comment by geek-yang** [comment]
Hi Peter,

Thanks for your comment! Sorry that I forgot we got another 404 issue. I will work on it then and get back to you if it is fixed!

**Comment by geek-yang** [comment]
Hi Peter, just quickly go through issue #6 and search a bit on dynamic routing. I think the post you found and pasted in the issue provides the solution we need (add 404.html to static and create a middleware for redirection). Do you want to also test and include that change in this PR? Or maybe we'd better open another one?

**Comment by Peter9192** [comment]
Let's add it here

**Comment by geek-yang** [comment]
Fixed！

**Review by Peter9192 — APPROVED** [review]
Nice one, I'm really curious to see if this works.

Might be nice to add custom error pages for paths that really don't exist, like `eucp-project.github.io/usecases/some/random/path.html`. See https://nuxtjs.org/docs/2.x/concepts/views#error-page

**Pull request merged**
